name: "Feature Request"
description: "새로운 기능 추가"
labels: ["feature"]
body:
  - type: textarea
    attributes:
      label: 📄 설명
      description: 새로운 기능에 대한 설명을 작성해 주세요.
      placeholder: |
        예시:
        - [ ] 

        자세히 적을수록 좋습니다!
    validations:
      required: true

  - type: textarea
    attributes:
      label: ✅ 작업할 내용
      description: 할 일을 체크박스 형태로 작성해주세요.
      placeholder: |
        백엔드 작업:
        - [ ] 

        데이터베이스:
        - [ ] 
        
        테스트:
        - [ ] 
        
        최대한 세분화해서 적어주세요!
    validations:
      required: true

  - type: textarea
    attributes:
      label: 🙋🏻 참고 자료
      description: 참고 자료가 있다면 작성해 주세요.
      placeholder: |
        관련 이슈:
        - [ ] #Issue